

server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trade?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 111111
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000ms     # 连接超时时间（毫秒） 建立连接的最长的等待时间。使用负值无限期等待
      lettuce:
        pool:
          max-active: 8   # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 8     # 连接池中的最大空闲连接
          min-idle: 0     # 连接池中的最小空闲连接
          max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
  threads:
    virtual:
      enabled: true

mybatis:
  mapper-locations: classpath*:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


